/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_EventInterface */

#ifndef _Included_net_java_games_input_EventInterface
#define _Included_net_java_games_input_EventInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_EventInterface
 * Method:    eventInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_eventInit
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getNumDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getNumDevices
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getFFEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_input_EventInterface_getFFEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_input_EventInterface_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    rumble
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_rumble
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getBusType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getBusType
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getVendorID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getVendorID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getProductID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getProductID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getSupportedRelAxes
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_getSupportedRelAxes
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getSupportedAbsAxes
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_getSupportedAbsAxes
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getSupportedButtons
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_getSupportedButtons
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    poll
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_poll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getPolledData
 * Signature: (I[I[I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_getPolledData
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getAbsAxisMinimum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getAbsAxisMinimum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getAbsAxisMaximum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getAbsAxisMaximum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getAbsAxisFuzz
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getAbsAxisFuzz
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    isValidDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_isValidDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    cleanup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_EventInterface_cleanup
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getNumberRelAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getNumberRelAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getNumberAbsAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getNumberAbsAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_EventInterface
 * Method:    getNumberButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_EventInterface_getNumberButtons
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
